# Define the goal
hexapod_control/Pose goal
float64 eps
---
# Define the result
hexapod_control/Pose finalPose
float64 error
float64 time
int32 errorCode
---
# Define a feedback message
hexapod_control/Pose target
hexapod_control/Pose currentPose
float64 error
float64 time