hexapod:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  leg_L1:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L1_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L1_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L1_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R1:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R1_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R1_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R1_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_L2:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L2_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L2_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L2_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R2:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R2_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R2_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R2_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_L3:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L3_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L3_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: L3_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R3:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R3_hip_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R3_knee_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: R3_ankle_joint
      pid: {p: 200.0, i: 1.0, d: 10.0}