hexapod:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  leg_L1:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_L1
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_L1
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_L1
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_L2:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_L2
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_L2
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_L2
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_L3:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_L3
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_L3
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_L3
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R1:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_R1
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_R1
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_R1
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R2:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_R2
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_R2
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_R2
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_R3:
    hip1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip1_R3
      pid: {p: 200.0, i: 1.0, d: 10.0}
    hip2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip2_R3
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_R3
      pid: {p: 200.0, i: 1.0, d: 10.0}