walking:
  linear_velocity: 0.04
  linear_acceleration: 0.02
  angular_velocity: 0.02 # TODO: edit this value
  angular_acceleration: 0.01 # TODO: edit this value
  duty_factor: 0.667
  stride_time: 1.0
  stride_height: 0.02
  relative_phase: [0.333, 0, 0.667, 0.333, 0, 0.667] # L1, R1, L2, R2, L3, R3