# Update these values based on hexapod.urdf.xacro
base:
  radius: 0.08
  height: 0.04
foot:
  radius: 0.16464
leg_L1:
  hip_angle: 120
leg_R1:
  hip_angle: 60
leg_L2:
  hip_angle: 180
leg_R2:
  hip_angle: 0
leg_L3:
  hip_angle: 240
leg_R3:
  hip_angle: 300