# Update these values based on hexapod.urdf.xacro
leg_L1:
  foot:
    x: -0.08232
    y: 0.1426
    z: -0.04
  hip:
    x: -0.04
    y: 0.069282
    z: 0.0
leg_R1:
  foot:
    x: 0.08232
    y: 0.1426
    z: -0.04
  hip:
    x: 0.04
    y: 0.069282
    z: 0.0
leg_L2:
  foot:
    x: -0.16464
    y: 0.0
    z: -0.04
  hip:
    x: -0.08
    y: 0.0
    z: 0.0
leg_R2:
  foot:
    x: 0.16464
    y: 0.0
    z: -0.04
  hip:
    x: 0.08
    y: 0.0
    z: 0.0
leg_L3:
  foot:
    x: -0.08232
    y: -0.1426
    z: -0.04
  hip:
    x: -0.04
    y: -0.069282
    z: 0.0
leg_R3:
  foot:
    x: 0.08232
    y: -0.1426
    z: -0.04
  hip:
    x: 0.04
    y: -0.069282
    z: 0.0