# Define the goal
string gait_mode
geometry_msgs/Twist base_twist
float64 hex_pos
float64 hex_heading
float64 hex_rot
---
# Define the result
float64 distance
float64 time
---
# Define the feedback message
int32 stage
string description
float64 distance
float64 time